apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-client
  namespace: italy
  labels:
    app: email-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-client
  template:
    metadata:
      labels:
        app: email-client
    spec:
      containers:
      - name: email-client
        image: sajeeth1009/email-client-service-image:v0.9.1
        imagePullPolicy: Always
        env:
        - name: EMAIL_CLIENT_SERVICE_LISTEN_PORT
          value: "5005"
        - name: MESSAGING_CONFIG_FOLDER
          value: "/config"
        volumeMounts:
        - name: config-volume
          mountPath: /config/
        ports:
        - containerPort: 5005
          protocol: TCP
        - containerPort: 465
          name: smtpssl
          protocol: TCP
        - containerPort: 587
          name: smtpauth
          protocol: TCP
        resources:
          requests:
            cpu: 30m
            memory: 150Mi
          limits:
            cpu: 100m
            memory: 300Mi
      volumes:
      - name: config-volume
        configMap:
          name: email-server-config