apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-scheduler
  namespace: belgium
  labels:
    app: message-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-scheduler
  template:
    metadata:
      labels:
        app: message-scheduler
    spec:
      containers:
      - name: message-scheduler
        image: sajeeth1009/message-scheduler-image:v0.9.0
        imagePullPolicy: Always
        env:
        - name: GLOBAL_DB_CONNECTION_STR
          value: mongo-atlas-service:27017
        - name: GLOBAL_DB_CONNECTION_PREFIX
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: connectionPrefix
        - name: GLOBAL_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: username
        - name: GLOBAL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: password
        - name: MESSAGE_DB_CONNECTION_STR
          value: mongo-atlas-service:27017
        - name: MESSAGE_DB_CONNECTION_PREFIX
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: connectionPrefix
        - name: MESSAGE_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: username
        - name: MESSAGE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: password
        - name: DB_TIMEOUT
          value: "30"
        - name: DB_IDLE_CONN_TIMEOUT
          value: "46"
        - name: DB_MAX_POOL_SIZE
          value: "8"
        - name: DB_DB_NAME_PREFIX
          value: ""
        - name: MESSAGE_SCHEDULER_INTERVAL_HIGH_PRIO
          value: "45"
        - name: MESSAGE_SCHEDULER_INTERVAL_LOW_PRIO
          value: "1800"
        - name: MESSAGE_SCHEDULER_INTERVAL_AUTO_MESSAGE
          value: "120"
        - name: ADDR_USER_MANAGEMENT_SERVICE
          value: user-management-service:5002
        - name: ADDR_STUDY_SERVICE
          value: study-service:5003
        - name: ADDR_EMAIL_CLIENT_SERVICE
          value: email-client-service:5005
        resources:
          requests:
            cpu: 30m
            memory: 150Mi
          limits:
            cpu: 100m
            memory: 300Mi