apiVersion: apps/v1
kind: Deployment
metadata:
  name: study
  namespace: belgium
  labels:
    app: study
spec:
  replicas: 1
  selector:
    matchLabels:
      app: study
  template:
    metadata:
      labels:
        app: study
    spec:
      containers:
      - name: study
        image: infectieradarbe/study-service-image:v0.13.2
        env:
        - name: STUDY_SERVICE_LISTEN_PORT
          value: "5003"
        - name: DB_TIMEOUT
          value: "30"
        - name: DB_IDLE_CONN_TIMEOUT
          value: "46"
        - name: DB_MAX_POOL_SIZE
          value: "8"
        - name: DB_DB_NAME_PREFIX
          value: ""
        - name: GLOBAL_DB_CONNECTION_STR
          value: mongo-atlas-service:27017
        - name: GLOBAL_DB_CONNECTION_PREFIX
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: connectionPrefix
        - name: GLOBAL_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: username
        - name: GLOBAL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: password
        - name: STUDY_DB_CONNECTION_STR
          value: mongo-atlas-service:27017
        - name: STUDY_DB_CONNECTION_PREFIX
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: connectionPrefix
        - name: STUDY_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: username
        - name: STUDY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: password
        - name: STUDY_TIMER_EVENT_FREQUENCY
          value: "2"
        - name: STUDY_TIMER_EVENT_CHECK_INTERVAL_MIN
          value: "2"
        - name: STUDY_TIMER_EVENT_CHECK_INTERVAL_VAR
          value: "1"
        - name: STUDY_GLOBAL_SECRET
          value: ""
        - name: ADDR_LOGGING_SERVICE
          value: logging-service:5006
        ports:
        - containerPort: 5003
        resources:
          requests:
            cpu: 30m
            memory: 150Mi
          limits:
            cpu: 100m
            memory: 300Mi

