apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
  namespace: italy
  labels:
    app: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
      - name: user-management
        image: sajeeth1009/user-management-image:v0.19.2
        env:
        - name: USER_MANAGEMENT_LISTEN_PORT
          value: "5002"
        - name: DB_TIMEOUT
          value: "30"
        - name: DB_IDLE_CONN_TIMEOUT
          value: "46"
        - name: DB_MAX_POOL_SIZE
          value: "8"
        - name: DB_DB_NAME_PREFIX
          value: ""
        - name: GLOBAL_DB_CONNECTION_STR
          value: mongo-atlas-service:27017
        - name: GLOBAL_DB_CONNECTION_PREFIX
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: connectionPrefix
        - name: GLOBAL_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: username
        - name: GLOBAL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: password
        - name: USER_DB_CONNECTION_STR
          value: mongo-atlas-service:27017
        - name: USER_DB_CONNECTION_PREFIX
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: connectionPrefix
        - name: USER_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: username
        - name: USER_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: case-mongodb-atlas
              key: password
        - name: TOKEN_EXPIRATION_MIN
          value: "5"
        - name: TOKEN_MINIMUM_AGE_MIN
          value: "2"
        - name: JWT_TOKEN_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-collection
              key: jwt-key
        - name: ARGON2_MEMORY
          value: "65536"
        - name: ARGON2_ITERATIONS
          value: "4"
        - name: ARGON2_PARALLELISM
          value: "2"
        - name: ADDR_MESSAGING_SERVICE
          value: messaging-service:5004
        - name: ADDR_LOGGING_SERVICE
          value: logging-service:5006
        - name: NEW_USER_RATE_LIMIT
          value: "100"
        - name: CLEAN_UP_UNVERIFIED_USERS_AFTER
          value: "129000"
        - name: VERIFICATION_CODE_LIFETIME
          value: "900"
        ports:
        - containerPort: 5002
        resources:
          requests:
            cpu: 30m
            memory: 150Mi
          limits:
            cpu: 150m
            memory: 300Mi

