apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
  namespace: case
  labels:
    app: web-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      containers:
      - name: web-client
        image: sajeeth1009/web-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3100
