apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
  namespace: belgium
  labels:
    app: web-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      containers:
      - name: web-client
        image: sajeeth1009/web-client-image:v0.24.6
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: web-env-config
        ports:
        - containerPort: 3100
        resources:
          requests:
            cpu: 30m
            memory: 150Mi
          limits:
            cpu: 150m
            memory: 300Mi
