apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-site
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sajeeth.sadananda@isi.it
    privateKeySecretRef:
      name: letsencrypt-prod-site
    solvers:
    - http01:
        ingress:
          class: nginx
