apiVersion: v1
kind: Service
metadata:
  name: email-client-service
  namespace: belgium
spec:
  type: ClusterIP
  selector:
    app: email-client
  ports:
  - name: grpc
    protocol: TCP
    port: 5005
    targetPort: 5005