apiVersion: v1
kind: Service
metadata:
  namespace: belgium
  name: study-service
spec:
  type: ClusterIP
  selector:
    app: study
  ports:
  - name: grpc
    protocol: TCP
    port: 5003
    targetPort: 5003
