apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
  namespace: case
  labels:
    app: web-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      containers:
      - name: web-client
        image: sajeeth1009/participant-webapp:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3100
<<<<<<< HEAD:deployments/web-client-deployment.yaml
=======
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 300m
            memory: 350Mi
>>>>>>> upstream/master:archived/deployments/web-client-deployment.yaml
