apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mailgun
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  tls:
  - secretName: {{ .Values.tlsSecretName }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - backend:
              service:
                name: mailgun-webhook-service
                port:
                  number: 8080
            path: {{ tpl .Values.endpoint . }}
            pathType: ImplementationSpecific