{{- range .Values.microservices }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .deployment.name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ .deployment.name }}
spec: {{ toJson .deployment.spec }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .service.name}}
  namespace: {{ $.Values.namespace }}
spec: {{ toJson .service.spec }}
{{- end }}