{{ if .Values.svcMongoDb.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.svcMongoDb.pvClaimName }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.svcMongoDb.storageClass }}
  accessModes: {{ .Values.svcMongoDb.accessModes }}
  resources:
    requests:
      storage: {{ .Values.svcMongoDb.storageRequested }}
{{ end }}