{{ if eq .Values.createStorageClass true }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.svcMongoDb.storageClass }}
  namespace: {{ .Values.namespace }}
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
{{ end }}