apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: migration-pv-claim
  namespace: {{ .Values.namespace | quote }}
spec:
  storageClassName: influenzanet-migration
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi