apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: influenzanet-migration
  namespace: {{ .Values.namespace }}
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer