apiVersion: v1
kind: Service
metadata:
  name: logging-service
  namespace: case
spec:
  type: ClusterIP
  selector:
    app: logging
  ports:
  - name: grpc
    protocol: TCP
    port: 5006
    targetPort: 5006