apiVersion: v1
kind: Service
metadata:
  name: participant-api-service
  namespace: case
spec:
  type: NodePort
  selector:
    app: participant-api
  ports:
  - name: grpc
    protocol: TCP
    port: 3231
    targetPort: 3231
