apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  namespace: case
spec:
  type: ClusterIP
  selector:
    app: user-management
  ports:
  - name: grpc
    protocol: TCP
    port: 5002
    targetPort: 5002