apiVersion: v1    
kind: Secret
metadata:
    name: jwt-collection
    namespace: italy
type: Opaque
data:
    jwt-key: ""
---
apiVersion: v1    
kind: Secret
metadata:
    name: case-mongodb-atlas
    namespace: italy
type: kubernetes.io/basic-auth
stringData:
    username: "admin"
    password: "abc123"
    connectionPrefix: ""
---
apiVersion: v1    
kind: Secret
metadata:
    name: recaptcha-collection
    namespace: italy
type: Opaque
data:
    recaptchaKey: "<insert-base64-key-here>"
